"""Press game hotkeys (I = inventory, C = log) to open/close panels for reading.

Deskrawl (Unity) ignores keyboard messages posted to its window while it is not focused, so
real input via SendInput is needed, and that always goes to the foreground window. Two modes:
  * only while Deskrawl already has focus - never touches other programs
  * briefly focus Deskrawl, press, and give focus back - works while you are in another
    program, but interrupts it for about a second (fullscreen games may minimize)
"""
import ctypes
import ctypes.wintypes as W
import time

user32 = ctypes.windll.user32
user32.GetForegroundWindow.restype = W.HWND
user32.SetForegroundWindow.argtypes = [W.HWND]
user32.IsWindow.argtypes = [W.HWND]

INPUT_KEYBOARD = 1
KEYEVENTF_KEYUP = 0x2
KEYEVENTF_SCANCODE = 0x8
VK_MENU = 0x12


class KEYBDINPUT(ctypes.Structure):
    _fields_ = [("wVk", W.WORD), ("wScan", W.WORD), ("dwFlags", W.DWORD), ("time", W.DWORD),
                ("dwExtraInfo", ctypes.c_void_p)]


class _INPUTUNION(ctypes.Union):
    # MOUSEINPUT is the largest member; pad so sizeof(INPUT) matches Windows (40 bytes on x64)
    _fields_ = [("ki", KEYBDINPUT), ("_pad", ctypes.c_byte * 32)]


class INPUT(ctypes.Structure):
    _fields_ = [("type", W.DWORD), ("u", _INPUTUNION)]


def _key(vk: int, up: bool, scancode: bool = True):
    sc = user32.MapVirtualKeyW(vk, 0)
    flags = (KEYEVENTF_SCANCODE if scancode else 0) | (KEYEVENTF_KEYUP if up else 0)
    inp = INPUT(INPUT_KEYBOARD)
    inp.u.ki = KEYBDINPUT(0 if scancode else vk, sc if scancode else 0, flags, 0, None)
    user32.SendInput(1, ctypes.byref(inp), ctypes.sizeof(INPUT))


def tap(key: str):
    vk = ord(key.upper())
    _key(vk, False)
    time.sleep(0.04)
    _key(vk, True)


def is_foreground(hwnd) -> bool:
    return bool(hwnd) and user32.GetForegroundWindow() == hwnd


def focus(hwnd) -> bool:
    """SetForegroundWindow is refused for background processes unless a key event was just
    generated by this process; a lone Alt tap satisfies that rule."""
    if is_foreground(hwnd):
        return True
    _key(VK_MENU, False, scancode=False)
    _key(VK_MENU, True, scancode=False)
    user32.SetForegroundWindow(hwnd)
    for _ in range(20):
        if is_foreground(hwnd):
            return True
        time.sleep(0.02)
    return False


def press_keys(hwnd, keys: list[str], allow_focus_switch: bool):
    """Press keys in the game. Returns the previously focused window if focus was switched
    (pass it to restore_focus), True if pressed without switching, or None if not pressed."""
    if not keys:
        return True
    if is_foreground(hwnd):
        for k in keys:
            tap(k)
            time.sleep(0.05)
        return True
    if not allow_focus_switch:
        return None
    prev = user32.GetForegroundWindow()
    if not focus(hwnd):
        return None
    for k in keys:
        tap(k)
        time.sleep(0.05)
    return prev


def restore_focus(prev):
    if prev and prev is not True and user32.IsWindow(prev):
        focus(prev)


# ----------------------------------------------------------------------------- background attempt
WM_ACTIVATEAPP, WM_ACTIVATE, WM_SETFOCUS, WM_KILLFOCUS = 0x001C, 0x0006, 0x0007, 0x0008
WM_KEYDOWN, WM_KEYUP, WM_CHAR = 0x0100, 0x0101, 0x0102
user32.SendMessageW.argtypes = [W.HWND, W.UINT, W.WPARAM, W.LPARAM]
user32.PostMessageW.argtypes = [W.HWND, W.UINT, W.WPARAM, W.LPARAM]


def press_keys_background(hwnd, keys: list[str]):
    """Try to press keys without taking focus: tell the window it is active (Unity drops key
    messages while it thinks it is unfocused), post the key messages, then tell it it lost focus
    again. Whether the game accepts this can only be verified by looking at the result."""
    user32.SendMessageW(hwnd, WM_ACTIVATEAPP, 1, 0)
    user32.SendMessageW(hwnd, WM_ACTIVATE, 1, 0)  # WA_ACTIVE
    user32.SendMessageW(hwnd, WM_SETFOCUS, 0, 0)
    time.sleep(0.05)
    for k in keys:
        vk = ord(k.upper())
        sc = user32.MapVirtualKeyW(vk, 0)
        user32.PostMessageW(hwnd, WM_KEYDOWN, vk, 1 | (sc << 16))
        user32.PostMessageW(hwnd, WM_CHAR, ord(k.lower()), 1 | (sc << 16))
        time.sleep(0.06)
        user32.PostMessageW(hwnd, WM_KEYUP, vk, 1 | (sc << 16) | (1 << 30) | (1 << 31))
        time.sleep(0.06)
    time.sleep(0.15)  # let the game process the keys while it believes it has focus
    user32.SendMessageW(hwnd, WM_KILLFOCUS, 0, 0)
    user32.SendMessageW(hwnd, WM_ACTIVATE, 0, 0)  # WA_INACTIVE
    user32.SendMessageW(hwnd, WM_ACTIVATEAPP, 0, 0)


# ----------------------------------------------------------------------------- hide without minimizing
# A minimized window is not rendered, so nothing can be read from it. Instead the game window is
# made fully transparent (it is a layered, click-through window already): it keeps running and
# rendering, the tracker can read it, but it is invisible and does not block anything.
GWL_EXSTYLE, WS_EX_LAYERED, LWA_ALPHA = -20, 0x80000, 0x2
user32.SetLayeredWindowAttributes.argtypes = [W.HWND, W.DWORD, ctypes.c_ubyte, W.DWORD]
user32.GetLayeredWindowAttributes.argtypes = [W.HWND, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p]
user32.GetWindowLongW.argtypes = [W.HWND, ctypes.c_int]
user32.SetWindowLongW.argtypes = [W.HWND, ctypes.c_int, ctypes.c_long]
user32.ShowWindow.argtypes = [W.HWND, ctypes.c_int]
user32.IsIconic.argtypes = [W.HWND]


def is_hidden(hwnd) -> bool:
    alpha, flags = ctypes.c_ubyte(), W.DWORD()
    if not user32.GetLayeredWindowAttributes(hwnd, None, ctypes.byref(alpha), ctypes.byref(flags)):
        return False
    return bool(flags.value & LWA_ALPHA) and alpha.value <= 1


def hide_game(hwnd):
    ex = user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
    if not ex & WS_EX_LAYERED:
        user32.SetWindowLongW(hwnd, GWL_EXSTYLE, ex | WS_EX_LAYERED)
    user32.SetLayeredWindowAttributes(hwnd, 0, 1, LWA_ALPHA)  # alpha 1/255: invisible, still rendered
    if user32.IsIconic(hwnd):
        user32.ShowWindow(hwnd, 4)  # SW_SHOWNOACTIVATE: un-minimize without taking focus


def show_game(hwnd):
    """Undo hide_game: re-adding WS_EX_LAYERED resets the alpha the tracker set."""
    ex = user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
    user32.SetWindowLongW(hwnd, GWL_EXSTYLE, ex & ~WS_EX_LAYERED)
    user32.SetWindowLongW(hwnd, GWL_EXSTYLE, ex | WS_EX_LAYERED)


WS_EX_TRANSPARENT = 0x20


def ensure_click_through(hwnd) -> bool:
    """Deskrawl drops WS_EX_TRANSPARENT while the cursor is over its own panels so they can be
    clicked - even when invisible. Put it back; returns True if it had to."""
    ex = user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
    if ex & WS_EX_TRANSPARENT:
        return False
    user32.SetWindowLongW(hwnd, GWL_EXSTYLE, ex | WS_EX_TRANSPARENT | WS_EX_LAYERED)
    return True
